# tablist
[plugin]
    enabled=true

# Global tablist
[global-tablist]
    enabled=true

[tablist-header-footer]
    update_ms=1000 # updates every 1000 milliseconds
    enabled=true
    # If you are unsure how to hanle new lines, take a look at https://toml.io/en/ or just use \n
    header="""
        &cExample Network

        &aLine 3!"""
    footer="&dhave fun!"

[developer-info]
    config-version=0.1

[join-message]
    use = true
    format = "#displayname# &ejoined"

[leave-message]
    use = true
    format = "#displayname# &eleft"